first commit14

diff --git a/contrib/snap/snapcraft.yaml b/contrib/snap/snapcraft.yaml
--- a/contrib/snap/snapcraft.yaml
+++ b/contrib/snap/snapcraft.yaml
@@ -1,9 +1,9 @@
-name: noncecash-core
+name: nerocash-core
 # Running 'snapcraft register <name>' is advised
 version: '1.14.6'
-summary: Reference client of NonceCash, a peer-to-peer digital currency like Bitcoin.
+summary: Reference client of Nerocash, a peer-to-peer digital currency like Bitcoin.
 description: |
-  NonceCash is a community-driven cryptocurrency that was inspired by a Shiba Inu meme. The NonceCash Core software allows anyone to operate a node in the NonceCash blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.
+  Nerocash is a community-driven cryptocurrency that was inspired by a Shiba Inu meme. The Nerocash Core software allows anyone to operate a node in the Nerocash blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.
 
 grade: stable
 confinement: strict
@@ -22,21 +22,21 @@ apps:
     command: noncecashd
     plugs: [home, removable-media, network, network-bind]
     environment:
-      # Override HOME so the datadir is located at ~/snap/noncecash-core/common/.noncecash/ instead of ~/snap/noncecash-core/current/.noncecash/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
+      # Override HOME so the datadir is located at ~/snap/nerocash-core/common/.nerocash/ instead of ~/snap/nerocash-core/current/.nerocash/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
       HOME: $SNAP_USER_COMMON
   qt:
-    command: desktop-launch noncecash-qt
+    command: desktop-launch nerocash-qt
     plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
     environment:
       HOME: $SNAP_USER_COMMON
       DISABLE_WAYLAND: 1
   cli:
-    command: noncecash-cli
+    command: nerocash-cli
     plugs: [home, removable-media, network]
     environment:
       HOME: $SNAP_USER_COMMON
   tx:
-    command: noncecash-tx
+    command: nerocash-tx
     plugs: [home, removable-media, network]
     environment:
       HOME: $SNAP_USER_COMMON
@@ -76,47 +76,47 @@ parts:
       - xdg-user-dirs
       - fcitx-frontend-qt5
 
-  noncecash-core:
+  nerocash-core:
     plugin: nil
     override-build: |
-      echo "This script is viewable at https://github.com/noncecash/noncecash/blob/master/contrib/snap/snapcraft.yaml"
+      echo "This script is viewable at https://github.com/nerocash/nerocash/blob/master/contrib/snap/snapcraft.yaml"
       echo "Downloading files..."
-      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but noncecash designates it as i686
+      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but nerocash designates it as i686
         BUILD_ARCH_TRIPLET=i686-pc-linux-gnu
       else
         BUILD_ARCH_TRIPLET=$SNAPCRAFT_ARCH_TRIPLET
       fi
-      wget https://github.com/noncecash/noncecash/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/noncecash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
-      wget https://github.com/noncecash/gitian.sigs/archive/refs/heads/master.tar.gz
+      wget https://github.com/nerocash/nerocash/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/nerocash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
+      wget https://github.com/nerocash/gitian.sigs/archive/refs/heads/master.tar.gz
       tar -xvf master.tar.gz
       echo "Verifying secure hash matches signed values..."
-      checksum=$(sha256sum noncecash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
-      if ! (grep -r $checksum * | grep noncecash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
+      checksum=$(sha256sum nerocash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
+      if ! (grep -r $checksum * | grep nerocash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
         echo "Secure hash not verified."
         return
       else
         echo "Secure hash verified."
       fi
-      tar -xvf noncecash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
+      tar -xvf nerocash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
       echo "Running tests..."
-      if ! (noncecash-${SNAPCRAFT_PROJECT_VERSION}/bin/test_noncecash); then
-        echo "NonceCash tests failed."
+      if ! (nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/test_noncecash); then
+        echo "Nerocash tests failed."
         return
       else
-        echo "NonceCash tests passed."
+        echo "Nerocash tests passed."
       fi
-      wget https://raw.githubusercontent.com/noncecash/noncecash/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
+      wget https://raw.githubusercontent.com/nerocash/nerocash/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
       cat release-notes.md
-      echo "Installing NonceCash Core..."
+      echo "Installing Nerocash Core..."
       echo "Version ${SNAPCRAFT_PROJECT_VERSION}"
-      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin noncecash-${SNAPCRAFT_PROJECT_VERSION}/bin/noncecashd
-      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official noncecash-qt build on arm64
-        install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin noncecash-${SNAPCRAFT_PROJECT_VERSION}/bin/noncecash-qt
+      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/noncecashd
+      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official nerocash-qt build on arm64
+        install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/nerocash-qt
       fi
-      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin noncecash-${SNAPCRAFT_PROJECT_VERSION}/bin/noncecash-cli
-      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin noncecash-${SNAPCRAFT_PROJECT_VERSION}/bin/noncecash-tx
-      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin noncecash-${SNAPCRAFT_PROJECT_VERSION}/bin/test_noncecash
-      wget https://raw.githubusercontent.com/noncecash/noncecash/master/share/pixmaps/noncecash128.png
+      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/nerocash-cli
+      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/nerocash-tx
+      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/test_noncecash
+      wget https://raw.githubusercontent.com/nerocash/nerocash/master/share/pixmaps/noncecash128.png
       install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps noncecash128.png
     build-packages:
       - wget
